#!/usr/bin/env python3
"""
Plot unique visits per day from a CSV file generated by extract_visits.py
Creates a bar diagram showing the number of unique visits each day.
"""

import click
import polars as pl
from pathlib import Path
from statistics import median


@click.command()
@click.argument('csv_file', type=click.Path(exists=True, file_okay=True, dir_okay=False))
@click.option(
    '--output',
    '-o',
    type=click.Path(),
    default=None,
    help='Output image file path (auto-generated if not specified, e.g., visits.png)'
)
@click.option(
    '--width',
    '-w',
    type=int,
    default=16,
    help='Figure width in inches (default: 16)'
)
@click.option(
    '--height',
    '-h',
    type=int,
    default=6,
    help='Figure height in inches (default: 6)'
)
@click.option(
    '--format',
    '-f',
    type=click.Choice(['png', 'pdf', 'svg']),
    default='png',
    help='Output image format (default: png)'
)
@click.option(
    '--title',
    '-t',
    default=None,
    help='Custom title for the plot'
)
@click.option(
    '--start-date',
    '-s',
    type=str,
    default=None,
    help='Start date for filtering (format: YYYY-MM-DD)'
)
@click.option(
    '--end-date',
    '-e',
    type=str,
    default=None,
    help='End date for filtering (format: YYYY-MM-DD)'
)
@click.option(
    '--show',
    is_flag=True,
    help='Display the plot in the default image viewer'
)
def plot_visits(
    csv_file: str,
    output: str,
    width: int,
    height: int,
    format: str,
    title: str,
    start_date: str,
    end_date: str,
    show: bool
):
    """
    Plot unique visits per day from CSV file.
    
    Creates a bar diagram showing the number of unique visitors each day.
    Supports filtering by date range.
    
    Example:
        ./plot_visits.py visits.csv -o visits_plot.png -w 20 -h 8
        ./plot_visits.py visits.csv -s 2024-06-01 -e 2024-08-31 -t "Summer Visits"
    """
    try:
        import matplotlib.pyplot as plt
        import matplotlib.dates as mdates
    except ImportError:
        click.echo("❌ matplotlib is not installed. Install it with:", err=True)
        click.echo("   pip install matplotlib", err=True)
        raise click.Abort()
    
    csv_path = Path(csv_file)
    
    # Read CSV file
    try:
        df = pl.read_csv(csv_path)
    except Exception as e:
        click.echo(f"❌ Error reading CSV file: {e}", err=True)
        raise click.Abort()
    
    # Validate columns
    required_cols = ['date', 'unique_visits']
    if not all(col in df.columns for col in required_cols):
        click.echo(f"❌ CSV must contain columns: {', '.join(required_cols)}", err=True)
        raise click.Abort()
    
    # Convert date column to datetime
    try:
        df = df.with_columns([
            pl.col('date').str.to_date()
        ])
    except Exception as e:
        click.echo(f"❌ Error parsing dates: {e}", err=True)
        raise click.Abort()
    
    # Apply date range filtering
    if start_date:
        try:
            from datetime import datetime
            start_date_obj = datetime.strptime(start_date, '%Y-%m-%d').date()
            df = df.filter(pl.col('date') >= start_date_obj)
            click.echo(f"📅 Start date filter: {start_date}")
        except Exception as e:
            click.echo(f"❌ Invalid start date format (use YYYY-MM-DD): {e}", err=True)
            raise click.Abort()
    
    if end_date:
        try:
            from datetime import datetime
            end_date_obj = datetime.strptime(end_date, '%Y-%m-%d').date()
            df = df.filter(pl.col('date') <= end_date_obj)
            click.echo(f"📅 End date filter: {end_date}")
        except Exception as e:
            click.echo(f"❌ Invalid end date format (use YYYY-MM-DD): {e}", err=True)
            raise click.Abort()
    
    # Check if any data remains after filtering
    if len(df) == 0:
        click.echo("❌ No data found in the specified date range", err=True)
        raise click.Abort()
    
    # Sort by date
    df = df.sort('date')
    
    # Create plot
    fig, ax = plt.subplots(figsize=(width, height))
    
    dates = df['date'].to_list()
    visits = df['unique_visits'].to_list()
    
    # Create bar plot
    ax.bar(dates, visits, color='steelblue', alpha=0.8, edgecolor='navy', linewidth=0.5)
    
    # Formatting
    ax.set_xlabel('Date', fontsize=12, fontweight='bold')
    ax.set_ylabel('Unique Visits', fontsize=12, fontweight='bold')
    
    if title:
        ax.set_title(title, fontsize=14, fontweight='bold')
    else:
        ax.set_title(f'Unique Visits per Day ({len(df)} days)', fontsize=14, fontweight='bold')
    
    # Format x-axis with dates
    ax.xaxis.set_major_locator(mdates.MonthLocator())
    ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'))
    fig.autofmt_xdate(rotation=45, ha='right')
    
    # Add grid
    ax.grid(axis='y', alpha=0.3, linestyle='--')
    ax.set_axisbelow(True)
    
    # Add statistics to plot
    min_visits = min(visits)
    max_visits = max(visits)
    avg_visits = sum(visits) / len(visits)
    median_visits = median(visits)
    
    stats_text = f'Min: {min_visits} | Median: {median_visits} | Avg: {avg_visits:.0f} | Max: {max_visits}'
    ax.text(0.5, 0.95, stats_text, transform=ax.transAxes, 
            ha='center', va='top', fontsize=10, 
            bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))
    
    # Tight layout
    plt.tight_layout()
    
    # Determine output filename
    if output is None:
        output = csv_path.stem + f'_plot.{format}'
    else:
        if not output.endswith(f'.{format}'):
            output = f"{output}.{format}"
    
    output_path = Path(output)
    
    # Save plot
    try:
        plt.savefig(output_path, dpi=100, format=format, bbox_inches='tight')
        click.echo(f"✓ Plot saved to {output_path}")
    except Exception as e:
        click.echo(f"❌ Error saving plot: {e}", err=True)
        raise click.Abort()
    
    # Display statistics
    click.echo(f"\n📊 Plot Statistics:")
    click.echo(f"   Days analyzed: {len(df)}")
    click.echo(f"   Min visits: {min_visits}")
    click.echo(f"   Median visits: {median_visits}")
    click.echo(f"   Avg visits: {avg_visits:.1f}")
    click.echo(f"   Max visits: {max_visits}")
    click.echo(f"   Total visits: {sum(visits):,}")
    
    # Show plot if requested
    if show:
        click.echo("\n📈 Opening plot in default viewer...")
        plt.show()
    else:
        plt.close()


if __name__ == '__main__':
    plot_visits()
